import numpy as np

class PoscarWriter:
    @staticmethod
    def write(filename, lattice, positions, elements, counts, coordinate_system="Direct", title="Generated by ML"):
        """
        Writes a VASP POSCAR file.
        coordinate_system: "Direct" or "Cartesian"
        """
        with open(filename, 'w') as f:
            f.write(f"{title}\n")
            f.write("1.0\n")

            # Write Lattice
            for row in lattice:
                f.write(f" {row[0]:.10f} {row[1]:.10f} {row[2]:.10f}\n")

            # Write Elements
            f.write(" ".join(elements) + "\n")
            f.write(" ".join(map(str, counts)) + "\n")

            # Write Coordinate Type
            if coordinate_system.lower().startswith('d'):
                f.write("Direct\n")
            else:
                f.write("Cartesian\n")

            # Write Positions
            for pos in positions:
                f.write(f" {pos[0]:.10f} {pos[1]:.10f} {pos[2]:.10f}\n")
        print(f"Saved {filename}")

